Q2
aqattan/homework10 pull request #2
Opened 2016-10-12 15:51 UTC by aqattan

2016-10-12 15:57 UTC, malkhafaji commented on Q2.txt
> +while (x>0){
it should be x >= 0 since 0 is a valid element position in the array, otherwise, x > 0 will skip 0

2016-10-12 15:58 UTC, malkhafaji commented on Q2.txt
> +	x=x-1;
it seems redundant to do x - 2 then x - 1 in the same iteration. Just print a[x] then do x -= 3

2016-10-13 13:23 UTC, ssharba requested changes

2016-10-13 13:23 UTC, ssharba commented on Q2.txt
> +	x=x-1;
this will shift only one position

2016-10-13 18:17 UTC, malkhafaji commented
This is good to go, but I don't know how to merge this because I don't have write permission

2016-10-13 18:27 UTC, closed without merging